"""empty message

Revision ID: 5e7d6775dd75
Revises: ce5e984f5190
Create Date: 2024-08-28 15:37:41.449450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7d6775dd75'
down_revision = 'ce5e984f5190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media', sa.String(length=120), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('media')

    # ### end Alembic commands ###
